all:
  hosts:
    first_vm:
      ansible_host: 192.168.0.23
      ansible_user: ansible
      ansible_password: 123qwe123
      ansible_connection: ssh
      ansible_port: 22
    second_vm:
      ansible_host: 192.168.0.27
      ansible_user: ansible
      ansible_password: 123qwe123
      ansible_connection: ssh
      ansible_port: 22
    tretiy_vm:
      ansible_host: 192.168.0.28
      ansible_user: ansible
      ansible_password: 123qwe123
      ansible_connection: ssh
      ansible_port: 22